# Generated by Django 4.0.5 on 2022-06-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comment_remove_post_distance_upvote_downvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
